### ISSUE TITLE
Desaparición de artículos de 3 cofres

### ISSUE THREAD

**Issue by ferxexes** [HeberonYT/LESDM#1]
heberon buenas tardes.

de tu apoyo para revisar que paso con los articulos que estaban dentro de 3 cofres en mi plot, son 3 de madera y 1 de hierro, desaparecieron cosas como perlas ender, la rematadora(espada), herramientas encantadas, y armas, y gran cantidad de objetos varios que recogi en la dungeon, hoy me volvi a conectar y los encontre vacios, te comento que nadie esta de invitado en mi plot y nadie tiene acceso, le reporte el caso a hebert y me dijo que te avisaria.

me ayudas por favor.
2017-01-17_16 29 23
2017-01-17_16 40 44

te agradezco.

**Comment by ferxexes** [comment]
https://cloud.githubusercontent.com/assets/24999632/22043992/fc13ec66-dcd7-11e6-9c82-0fbde0a5d50f.png

**Comment by ferxexes** [comment]
Espero se pueda solucionar jejej si no pues olo mejora los bugs que pudieran tener esos cofres saludos

**Comment by HeberonYT** [comment]
Se investigó el problema pero no se encontró ningún error, para evitar robos futuros activa el siguiente permiso en tu Town **`/town perm set enter false`**
De esa manera ningún usuarios podrá entrar a tu Town, solo las personas que estén agregadas o que les otorgues permiso.
