### ISSUE TITLE
Ayuda y Dudas sobre lesdm 2

### ISSUE THREAD

**Issue by ferxexes** [HeberonYT/LESDM#2]
Heberon buen día. 

Tengo un problema cada que me spawneo al spawn, me tengo que desconectar porque sigo en el juego pero no puedo interactuar, es como un tipo de la go algo así, también cada que cambio de dimensión debo activar el modo fly nuevamente, soy Ferxexes Vip en el server.

Algunas preguntas y dudas.

.... cuales son los artículos que vienen en el kit vip, ya que no recibí los del tinkers, solo los de kit vip.

...porque el spawn de vacas no funciona correctamente?

...sabes de algún tutoríal o video donde vengas los comandos y como utilizarlos ( los del server de lesdm de rangos vip y titán )

.....aparte del tp, hay alguna forma de ir a puntos específicos del mapa sin necesidad de caminar o volar, ya que no está activado el warp book.

Sorry por tanta duda pero me encanta el server y todo es por mejorar y divertirme más.

Saludos

**Comment by HeberonYT** [comment]
Hola!
El primer problema que reportas, de no poder interactuar cuando vas al Spawn o a otra dimensión, no se ha reportado antes y no se logro replicar, quizás se deba a tu conexión o a lo lejano que estas del hosting.
El comando **`/fly`** debe activarse cada que entras.

Los artículos de cada kit se están actualizado debido al cambio de mods, pero estarán disponibles pronto y podrás obtener lo que se describe en la tienda de Buycraft.
Los comandos que puedes utilizar como VIP se describen en la misma pagina de rangos.

Para hacer TP utiliza el comando **`/tpa`** para mandar una solicitud a otro jugador, o utiliza los puntos Home que incluye tu rango.

**Comment by ferxexes** [comment]
Te agradezco tu atención
